version: '3.8'

services:
  # Chat Marketplace API Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    env_file:
      - .env
    environment:
      # PostgreSQL Configuration
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-chat_marketplace}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_ECHO=${POSTGRES_ECHO:-false}
      - POSTGRES_POOL_SIZE=${POSTGRES_POOL_SIZE:-10}
      - POSTGRES_MAX_OVERFLOW=${POSTGRES_MAX_OVERFLOW:-20}
      
      # Application Settings
      - APP_HOST=${APP_HOST:-0.0.0.0}
      - APP_PORT=${APP_PORT:-8080}
      - APP_ENV=${APP_ENV:-development}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # Security & CORS
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - CORS_METHODS=${CORS_METHODS:-GET,POST,PUT,DELETE,OPTIONS}
      - CORS_HEADERS=${CORS_HEADERS:-*}
      
      # Logging
      - LOG_FORMAT=${LOG_FORMAT:-%(asctime)s - %(name)s - %(levelname)s - %(message)s}
      - LOG_FILE=${LOG_FILE:-logs/app.log}
      - LOG_MAX_BYTES=${LOG_MAX_BYTES:-10485760}
      - LOG_BACKUP_COUNT=${LOG_BACKUP_COUNT:-5}
      
      # Admin Configuration
      - ADMIN_API_KEY=${ADMIN_API_KEY:-admin123}
      
      # App Info
      - APP_NAME=${APP_NAME:-Chat Marketplace Service}
      - APP_VERSION=${APP_VERSION:-2.0.0}
      
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT:-8080}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - chat-marketplace-network

  # PostgreSQL Database Service
  postgres:
    image: postgres:15-alpine
    container_name: chat_marketplace_postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-chat_marketplace}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-chat_marketplace}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - chat-marketplace-network

  # Redis (for caching and sessions) - Optional
  redis:
    image: redis:7-alpine
    container_name: chat_marketplace_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - chat-marketplace-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  chat-marketplace-network:
    driver: bridge
